In [1]:
import dart_fss
from dart_fss import get_corp_list

In [2]:
# 권한 설정
api_key='960a281f210548c84eb6c951ec3a10587b1ede65' 
dart_fss.set_api_key(api_key=api_key)

'960a281f210548c84eb6c951ec3a10587b1ede65'

In [3]:
corp_list = dart_fss.corp.get_corp_list()

In [4]:
a = corp_list.find_by_stock_code('219420')

Output()

Output()

In [5]:
a

[01109955]링크제니시스

In [18]:
fs_separate = a.extract_fs(bgn_de='20190101', separate=True)

TypeError: extract_fs() got an unexpected keyword argument 'header'

In [19]:
fs_separate

{'bgn_de': '20190101',
 'corp_code': '01109955',
 'end_de': None,
 'financial statement': [{'title': '[D210005] Statement of financial position, '
                                   'current/non-current - Separate financial '
                                   'statements (Unit: KRW)'},
                         {'title': 'is is None'},
                         {'title': '[D431415] Statement of comprehensive '
                                   'income, by function of expense - Separate '
                                   'financial statements (Unit: KRW)'},
                         {'title': '[D520005] Statement of cash flows, '
                                   'indirect method - Separate financial '
                                   'statements (Unit: KRW)'}],
 'lang': 'ko',
 'report_tp': 'annual',
 'separate': True,
 'separator': True}

In [7]:
len(fs_separate)

4

In [8]:
fs_separate[0]

   [D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)  \
                                                                                                   concept_id
0                             ifrs-full_CurrentAssets
1                    ifrs-full_CashAndCashEquivalents
2                                      ifrs-full_Cash
3                           ifrs-full_CashEquivalents
4   dart_ShortTermDepositsNotClassifiedAsCashEquiv...
..                                                ...
86                       dart_OtherCapitalAdjustments
87                         ifrs-full_RetainedEarnings
88  dart_RetainedEarningsBeforeAppropriationsAccum...
89                                   ifrs-full_Equity
90                     ifrs-full_EquityAndLiabilities

                                                                         \
            label_ko                                           label_en
0               유동자산                                     Current assets
1           현금및현금성자산                          Cash and cash equivalents
2                 현금                                               Cash
3              현금성자산                                   Cash equivalents
4             단기금융상품  Short-term deposits not classified as cash equ...
..               ...                                                ...
86            기타자본조정                          Other capital adjustments
87        이익잉여금(결손금)                                  Retained earnings
88  미처분이익잉여금(미처리결손금)  Retained earnings before appropriations(accumu...
89              자본총계                                       Total equity
90           자본과부채총계                       Total equity and liabilities

                                                                          \
              class0         class1      class2            class3 class4
0   재무상태표 [abstract]  자산 [abstract]        유동자산              None   None
1   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산   None
2   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산     현금
3   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산  현금성자산
4   재무상태표 [abstract]  자산 [abstract]        유동자산            단기금융상품   None
..               ...            ...         ...               ...    ...
86  재무상태표 [abstract]  자본 [abstract]    기타자본구성요소            기타자본조정   None
87  재무상태표 [abstract]  자본 [abstract]  이익잉여금(결손금)              None   None
88  재무상태표 [abstract]  자본 [abstract]  이익잉여금(결손금)  미처분이익잉여금(미처리결손금)   None
89  재무상태표 [abstract]  자본 [abstract]        자본총계              None   None
90  재무상태표 [abstract]        자본과부채총계        None              None   None

           20191231         20181231         20171231
          (별도재무제표,)        (별도재무제표,)        (별도재무제표,)
0  32,955,110,116.0 30,273,434,470.0 12,056,958,361.0
1   5,533,850,159.0  5,476,502,914.0  1,873,968,861.0
2   5,533,850,159.0  5,476,502,914.0  1,873,968,861.0
3               0.0              0.0              0.0
4   6,592,817,952.0        704,476.0        704,476.0
..              ...              ...              ...
86              0.0              0.0              0.0
87 11,699,764,709.0 10,925,300,637.0  9,077,180,277.0
88 11,699,764,709.0 10,925,300,637.0  9,077,180,277.0
89 33,902,111,135.0 30,667,602,849.0 13,162,787,958.0
90 36,987,002,532.0 35,310,621,389.0 15,185,044,543.0

[91 rows x 11 columns]

In [11]:
fs = fs_separate[0].fillna(method='ffill', axis=1)

In [66]:
fs

   [D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)  \
                                                                                                   concept_id
0                             ifrs-full_CurrentAssets
1                    ifrs-full_CashAndCashEquivalents
2                                      ifrs-full_Cash
3                           ifrs-full_CashEquivalents
4   dart_ShortTermDepositsNotClassifiedAsCashEquiv...
..                                                ...
86                       dart_OtherCapitalAdjustments
87                         ifrs-full_RetainedEarnings
88  dart_RetainedEarningsBeforeAppropriationsAccum...
89                                   ifrs-full_Equity
90                     ifrs-full_EquityAndLiabilities

                                                                         \
            label_ko                                           label_en
0               유동자산                                     Current assets
1           현금및현금성자산                          Cash and cash equivalents
2                 현금                                               Cash
3              현금성자산                                   Cash equivalents
4             단기금융상품  Short-term deposits not classified as cash equ...
..               ...                                                ...
86            기타자본조정                          Other capital adjustments
87        이익잉여금(결손금)                                  Retained earnings
88  미처분이익잉여금(미처리결손금)  Retained earnings before appropriations(accumu...
89              자본총계                                       Total equity
90           자본과부채총계                       Total equity and liabilities

                                                                   \
              class0         class1      class2            class3
0   재무상태표 [abstract]  자산 [abstract]        유동자산              유동자산
1   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산
2   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산
3   재무상태표 [abstract]  자산 [abstract]        유동자산          현금및현금성자산
4   재무상태표 [abstract]  자산 [abstract]        유동자산            단기금융상품
..               ...            ...         ...               ...
86  재무상태표 [abstract]  자본 [abstract]    기타자본구성요소            기타자본조정
87  재무상태표 [abstract]  자본 [abstract]  이익잉여금(결손금)        이익잉여금(결손금)
88  재무상태표 [abstract]  자본 [abstract]  이익잉여금(결손금)  미처분이익잉여금(미처리결손금)
89  재무상태표 [abstract]  자본 [abstract]        자본총계              자본총계
90  재무상태표 [abstract]        자본과부채총계     자본과부채총계           자본과부채총계

                             20191231         20181231         20171231
              class4        (별도재무제표,)        (별도재무제표,)        (별도재무제표,)
0               유동자산 32,955,110,116.0 30,273,434,470.0 12,056,958,361.0
1           현금및현금성자산  5,533,850,159.0  5,476,502,914.0  1,873,968,861.0
2                 현금  5,533,850,159.0  5,476,502,914.0  1,873,968,861.0
3              현금성자산              0.0              0.0              0.0
4             단기금융상품  6,592,817,952.0        704,476.0        704,476.0
..               ...              ...              ...              ...
86            기타자본조정              0.0              0.0              0.0
87        이익잉여금(결손금) 11,699,764,709.0 10,925,300,637.0  9,077,180,277.0
88  미처분이익잉여금(미처리결손금) 11,699,764,709.0 10,925,300,637.0  9,077,180,277.0
89              자본총계 33,902,111,135.0 30,667,602,849.0 13,162,787,958.0
90           자본과부채총계 36,987,002,532.0 35,310,621,389.0 15,185,044,543.0

[91 rows x 11 columns]

In [21]:
fs.columns

MultiIndex([('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            ('[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)', ...),
            (                                                                                                  '20191231', ...),
            (                                                                                                  '20181231', ...),
            (                                                                                                  '20171231', ...)],
           )

In [22]:
fs['class3']

KeyError: 'class3'

In [31]:
len(fs_separate[0].columns)

11

In [47]:
import pandas as pd

In [ ]:
fs['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class3'

In [24]:
pd.DataFrame(list(fs['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class3')]

SyntaxError: invalid syntax (<ipython-input-24-700f82c4bc7f>, line 2)

In [26]:
class3 = fs['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class2'].values

In [28]:
last = fs['20191231'].values

In [30]:
import pandas as pd

In [49]:
last = last.reshape(-1)

In [54]:
dict={'계정':list(class3),a.corp_name:list(last)}

In [55]:
fs1 = pd.DataFrame(dict)

In [56]:
fs1

            계정           링크제니시스
0         유동자산 32,955,110,116.0
1         유동자산  5,533,850,159.0
2         유동자산  5,533,850,159.0
3         유동자산              0.0
4         유동자산  6,592,817,952.0
..         ...              ...
86    기타자본구성요소              0.0
87  이익잉여금(결손금) 11,699,764,709.0
88  이익잉여금(결손금) 11,699,764,709.0
89        자본총계 33,902,111,135.0
90     자본과부채총계 36,987,002,532.0

[91 rows x 2 columns]

In [52]:
fs1['20191231']

0    32,955,110,116.0
1     5,533,850,159.0
2     5,533,850,159.0
3                 0.0
4     6,592,817,952.0
           ...
86                0.0
87   11,699,764,709.0
88   11,699,764,709.0
89   33,902,111,135.0
90   36,987,002,532.0
Name: 20191231, Length: 91, dtype: float64

In [75]:
fs_separate[0]['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class2'].values

array(['유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산',
       '유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산', '유동자산',
       '유동자산', '유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산',
       '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산',
       '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산',
       '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산',
       '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산', '비유동자산',
       '비유동자산', '비유동자산', '비유동자산', '비유동자산', '자산총계', '유동부채', '유동부채', '유동부채',
       '유동부채', '유동부채', '유동부채', '유동부채', '유동부채', '유동부채', '유동부채', '유동부채',
       '유동부채', '유동부채', '유동부채', '비유동부채', '비유동부채', '비유동부채', '비유동부채',
       '비유동부채', '비유동부채', '비유동부채', '부채총계', '자본금', '자본금', '자본금', '자본잉여금',
       '자본잉여금', '자본잉여금', '기타자본구성요소', '기타자본구성요소', '기타자본구성요소', '이익잉여금(결손금)',
       '이익잉여금(결손금)', '자본총계', None], dtype=object)

In [91]:
pd.DataFrame(fs_separate[0]['20191231'].values, columns=[a.corp_name])

             링크제니시스
0  32,955,110,116.0
1   5,533,850,159.0
2   5,533,850,159.0
3               0.0
4   6,592,817,952.0
..              ...
86              0.0
87 11,699,764,709.0
88 11,699,764,709.0
89 33,902,111,135.0
90 36,987,002,532.0

[91 rows x 1 columns]

In [131]:
df = pd.DataFrame([fs_separate[0]['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class2'].values,fs_separate[0]['[D210005] Statement of financial position, current/non-current - Separate financial statements (Unit: KRW)',
 'class3'].values,fs_separate[0]['20191231'].values]).T
# , columns=[['총계','계정',a.corp_name]])

In [59]:
fs_separate[2]

   [D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)  \
                                                                                                        concept_id
0                                   ifrs-full_Revenue
1                    ifrs-full_RevenueFromSaleOfGoods
2                  dart_RevenueFromSaleOfGoodsProduct
3            ifrs-full_RevenueFromRenderingOfServices
4                            dart_RevenueFromServices
..                                                ...
63                      ifrs-full_ComprehensiveIncome
64                ifrs-full_BasicEarningsLossPerShare
65  ifrs-full_BasicEarningsLossPerShareFromContinu...
66              ifrs-full_DilutedEarningsLossPerShare
67  ifrs-full_DilutedEarningsLossPerShareFromConti...

                                                                            \
               label_ko                                           label_en
0               수익(매출액)                                     Revenue(Sales)
1    재화의 판매로 인한 수익(매출액)                  Revenue(Saels) from sale of goods
2                 제품매출액                 Revenue from sale of goods product
3   용역의 제공으로 인한 수익(매출액)          Revenue(Sales) from rendering of services
4                 용역매출액                              Revenue from services
..                  ...                                                ...
63                총포괄손익                         Total comprehensive income
64           기본주당이익(손실)                    Basic earnings (loss) per share
65       계속영업기본주당이익(손실)  Basic earnings (loss) per share from continuin...
66           희석주당이익(손실)                  Diluted earnings (loss) per share
67       계속영업희석주당이익(손실)  Diluted earnings (loss) per share from continu...

                                                                              \
                class0           class1               class2          class3
0   포괄손익계산서 [abstract]          수익(매출액)                 None            None
1   포괄손익계산서 [abstract]          수익(매출액)   재화의 판매로 인한 수익(매출액)            None
2   포괄손익계산서 [abstract]          수익(매출액)   재화의 판매로 인한 수익(매출액)           제품매출액
3   포괄손익계산서 [abstract]          수익(매출액)  용역의 제공으로 인한 수익(매출액)            None
4   포괄손익계산서 [abstract]          수익(매출액)  용역의 제공으로 인한 수익(매출액)           용역매출액
..                 ...              ...                  ...             ...
63  포괄손익계산서 [abstract]            총포괄손익                 None            None
64  포괄손익계산서 [abstract]  주당이익 [abstract]           기본주당이익(손실)            None
65  포괄손익계산서 [abstract]  주당이익 [abstract]           기본주당이익(손실)  계속영업기본주당이익(손실)
66  포괄손익계산서 [abstract]  주당이익 [abstract]           희석주당이익(손실)            None
67  포괄손익계산서 [abstract]  주당이익 [abstract]           희석주당이익(손실)  계속영업희석주당이익(손실)

   20190101-20191231 20180101-20181231 20170101-20171231
           (별도재무제표,)         (별도재무제표,)         (별도재무제표,)
0   11,010,718,849.0  11,528,945,712.0  11,793,696,185.0
1    4,030,761,158.0   4,046,575,764.0   3,770,809,533.0
2    4,030,761,158.0   4,046,575,764.0   3,770,809,533.0
3    6,979,957,691.0   7,482,369,948.0   8,022,886,652.0
4    6,979,957,691.0   7,482,369,948.0   8,022,886,652.0
..               ...               ...               ...
63     774,464,072.0   2,331,642,763.0   2,710,324,733.0
64              80.0             240.0             287.0
65              80.0             240.0             287.0
66              80.0             232.0             287.0
67              80.0             232.0             287.0

[68 rows x 10 columns]

In [61]:
cis = fs_separate[2].fillna(method='ffill', axis=1)

In [63]:
cis.columns

MultiIndex([('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            ('[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)', ...),
            (                                                                                              '20190101-20191231', ...),
            (                                                                                              '20180101-20181231', ...),
            (                                                                                              '20170101-20171231', ...)],
           )

In [67]:
class3 = cis['[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)',
 'class2'].values

In [69]:
class3 = cis['[D431415] Statement of comprehensive income, by function of expense - Separate financial statements (Unit: KRW)',
 'class3'].values
last = cis['20190101-20191231'].values
last = last.reshape(-1)
dict={'계정':list(class3),a.corp_name:list(last)}
cis1 = pd.DataFrame(dict)

In [70]:
cis1

                     계정           링크제니시스
0               수익(매출액) 11,010,718,849.0
1    재화의 판매로 인한 수익(매출액)  4,030,761,158.0
2                 제품매출액  4,030,761,158.0
3   용역의 제공으로 인한 수익(매출액)  6,979,957,691.0
4                 용역매출액  6,979,957,691.0
..                  ...              ...
63                총포괄손익    774,464,072.0
64           기본주당이익(손실)             80.0
65       계속영업기본주당이익(손실)             80.0
66           희석주당이익(손실)             80.0
67       계속영업희석주당이익(손실)             80.0

[68 rows x 2 columns]

In [73]:
fs_separate[3]

   [D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)  \
                                                                                       concept_id
0    ifrs-full_CashFlowsFromUsedInOperatingActivities
1              dart_ProfitLossForStatementOfCashFlows
2         ifrs-full_AdjustmentsForReconcileProfitLoss
3   dart_AdjustmentsForLossesOnForeignExchangeTran...
4                  dart_AdjustmentsForBadDebtExpenses
..                                                ...
65                dart_RepaymentsOfLongTermBorrowings
66  ifrs-full_EffectOfExchangeRateChangesOnCashAnd...
67  ifrs-full_IncreaseDecreaseInCashAndCashEquival...
68   dart_CashAndCashEquivalentsAtBeginningOfPeriodCf
69         dart_CashAndCashEquivalentsAtEndOfPeriodCf

                                                                            \
               label_ko                                           label_en
0              영업활동현금흐름     Cash flows from (used in) operating activities
1             당기순이익(손실)                                      Profit (loss)
2        당기순이익조정을 위한 가감             Adjustments to reconcile profit (loss)
3                외화환산손실  Adjustments for losses on foreign exchange tra...
4                 대손상각비                  Adjustments for bad debt expenses
..                  ...                                                ...
65         유동성장기차입금의 상환                 Repayments of long term borrowings
66  현금및현금성자산에 대한 환율변동효과  Effect of exchange rate changes on cash and ca...
67     현금및현금성자산의순증가(감소)  Net increase (decrease) in cash and cash equiv...
68           기초현금및현금성자산   Cash and cash equivalents at beginning of period
69           기말현금및현금성자산         Cash and cash equivalents at end of period

                                                                   \
              class0               class1          class2  class3
0   현금흐름표 [abstract]             영업활동현금흐름            None    None
1   현금흐름표 [abstract]             영업활동현금흐름       당기순이익(손실)    None
2   현금흐름표 [abstract]             영업활동현금흐름  당기순이익조정을 위한 가감    None
3   현금흐름표 [abstract]             영업활동현금흐름  당기순이익조정을 위한 가감  외화환산손실
4   현금흐름표 [abstract]             영업활동현금흐름  당기순이익조정을 위한 가감   대손상각비
..               ...                  ...             ...     ...
65  현금흐름표 [abstract]             재무활동현금흐름    유동성장기차입금의 상환    None
66  현금흐름표 [abstract]  현금및현금성자산에 대한 환율변동효과            None    None
67  현금흐름표 [abstract]     현금및현금성자산의순증가(감소)            None    None
68  현금흐름표 [abstract]           기초현금및현금성자산            None    None
69  현금흐름표 [abstract]           기말현금및현금성자산            None    None

   20190101-20191231 20180101-20181231 20170101-20171231
           (별도재무제표,)         (별도재무제표,)         (별도재무제표,)
0      763,315,452.0   2,884,741,753.0   2,567,767,016.0
1      774,464,072.0   2,331,642,763.0   2,710,324,733.0
2    1,064,392,862.0     -67,310,312.0     381,909,862.0
3        9,440,061.0       6,704,394.0      16,976,830.0
4        5,868,385.0     -19,765,536.0         250,000.0
..               ...               ...               ...
65     424,999,992.0     124,999,992.0      83,333,360.0
66      -7,042,033.0       4,498,375.0     -13,698,548.0
67      57,347,245.0   3,602,534,053.0    -615,519,215.0
68   5,476,502,914.0   1,873,968,861.0   2,489,488,076.0
69   5,533,850,159.0   5,476,502,914.0   1,873,968,861.0

[70 rows x 10 columns]

In [74]:
fs_separate[3].columns

MultiIndex([('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            ('[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)', ...),
            (                                                                             '20190101-20191231', ...),
            (                                                                             '20180101-20181231', ...),
            (                                                                             '20170101-20171231', ...)],
           )

In [76]:
cf = fs_separate[3].fillna(method='ffill', axis=1)
class3 = cf['[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)',
 'class3'].values
last = cf['20190101-20191231'].values
last = last.reshape(-1)
dict={'계정':list(class3),a.corp_name:list(last)}
cf1 = pd.DataFrame(dict)

In [77]:
cf1

                     계정          링크제니시스
0              영업활동현금흐름   763,315,452.0
1             당기순이익(손실)   774,464,072.0
2        당기순이익조정을 위한 가감 1,064,392,862.0
3                외화환산손실     9,440,061.0
4                 대손상각비     5,868,385.0
..                  ...             ...
65         유동성장기차입금의 상환   424,999,992.0
66  현금및현금성자산에 대한 환율변동효과    -7,042,033.0
67     현금및현금성자산의순증가(감소)    57,347,245.0
68           기초현금및현금성자산 5,476,502,914.0
69           기말현금및현금성자산 5,533,850,159.0

[70 rows x 2 columns]

In [ ]:
a = corp_list.find_by_stock_code(i)
fs_separate = a.extract_fs(bgn_de=i, separate=True)
cf = fs_separate[3].fillna(method='ffill', axis=1)
class3 = cf['[D520005] Statement of cash flows, indirect method - Separate financial statements (Unit: KRW)',
 'class3'].values
last = cf['20190101-20191231'].values
last = last.reshape(-1)
dict={'계정':list(class3),a.corp_name:list(last)}
cis1 = pd.DataFrame(dict)

In [78]:
df = pd.DataFrame(columns=['계정'])

In [79]:
df

Empty DataFrame
Columns: [계정]
Index: []

In [82]:
pd.merge(df,cis1,how='inner',on='계정')

Empty DataFrame
Columns: [계정, 링크제니시스]
Index: []